src/Entity/Server.php
<?php

namespace App\Entity;

use App\Repository\ServerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ServerRepository::class)]
class Server
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;
    #[ORM\Column(type: 'text')]
    private $url;
    #[ORM\Column(type: 'text', nullable: true)]
    private $appId;
    #[ORM\Column(type: 'text', nullable: true)]
    private $appSecret;
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'servers')]
    private $user;
    #[ORM\OneToMany(targetEntity: Rooms::class, mappedBy: 'server')]
    private $rooms;
    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'serverAdmins')]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private $administrator;
    #[ORM\Column(type: 'text', nullable: true)]
    private $logoUrl;
    #[ORM\Column(type: 'text', nullable: true)]
    private $smtpHost;
    #[ORM\Column(type: 'integer', nullable: true)]
    private $smtpPort;
    #[ORM\Column(type: 'text', nullable: true)]
    private $smtpPassword;
    #[ORM\Column(type: 'text', nullable: true)]
    private $smtpUsername;
    #[ORM\Column(type: 'text', nullable: true)]
    private $smtpEncryption;
    #[ORM\Column(type: 'text', nullable: true)]
    private $smtpEmail;
    #[ORM\Column(type: 'text', nullable: true)]
    private $smtpSenderName;
    #[ORM\Column(type: 'text')]
    private $slug;
    #[ORM\Column(type: 'text', nullable: true)]
    private $privacyPolicy;
    #[ORM\Column(type: 'text', nullable: true)]
    private $licenseKey;
    #[ORM\Column(type: 'text', nullable: true)]
    private $apiKey;
    #[ORM\Column(type: 'string', length: 7, nullable: true)]
    private $staticBackgroundColor;
    #[ORM\Column(type: 'boolean', nullable: true)]
    private $showStaticBackgroundColor;
    #[ORM\Column(type: 'boolean', nullable: true)]
    private $featureEnableByJWT = false;
    #[ORM\Column(type: 'text', nullable: true)]
    private $serverEmailHeader;
    #[ORM\Column(type: 'text', nullable: true)]
    private $serverEmailBody;
    #[ORM\OneToMany(targetEntity: KeycloakGroupsToServers::class, mappedBy: 'server', cascade: ['persist'])]
    private $keycloakGroups;
    #[ORM\OneToMany(targetEntity: User::class, mappedBy: 'myOwnRoomServer')]
    private $OwnRoomUSer;
    #[ORM\Column(type: 'integer')]
    private $jwtModeratorPosition;
    #[ORM\Column(type: 'text')]
    private $serverName;
    #[ORM\Column(type: 'boolean', nullable: true)]
    private $corsHeader;
    #[ORM\OneToMany(targetEntity: Star::class, mappedBy: 'server', orphanRemoval: true)]
    private $stars;
    /**
     * @var Documents
     */
    #[ORM\OneToOne(targetEntity: Documents::class, cascade: ['persist', 'remove'])]
    private $serverBackgroundImage;
    #[ORM\Column(type: 'datetime', nullable: true)]
    private $updatedAt;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $jigasiApiUrl = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $jigasiNumberUrl = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $jigasiProsodyDomain = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $starUrl = null;

    #[ORM\Column(nullable: true)]
    private ?int $starServerId = null;

    #[ORM\Column(nullable: true)]
    private ?bool $disallowFirefox = null;

    #[ORM\Column(nullable: true)]
    private ?bool $enforceE2e = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $allowIp = null;

    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'servers')]
    private Collection $tag;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $dynamicBrandingUrl = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $jitsiEventSyncUrl = null;

    #[ORM\Column(nullable: true)]
    private ?bool $disableFilmstripe = null;

    #[ORM\Column(nullable: true)]
    private ?bool $disableEtherpad = null;

    #[ORM\Column(nullable: true)]
    private ?bool $disableWhiteboard = null;

    #[ORM\Column(nullable: true)]
    private ?bool $disableChat = null;

    #[ORM\Column(nullable: true)]
    private ?bool $prefixRoomUidWithHash = null;

    #[ORM\Column(nullable: true)]
    private ?bool $liveKitServer = null;

    #[ORM\Column(length: 512, nullable: true)]
    private ?string $livekitMiddlewareUrl = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $livekitBackgroundImages = "[
    {
      \"description\":\"\",
      \"url\": \"https://images.pexels.com/photos/27779028/pexels-photo-27779028/free-photo-of-landschaft-natur-himmel-wasser.jpeg\" 
    },
{
    \"description\":\"\",
      \"url\": \"https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg\" 
    },
{
    \"description\":\"\",
      \"url\":   \"https://images.pexels.com/photos/1450353/pexels-photo-1450353.jpeg\" 
    }
]";

    public function __construct()
    {
        $this->user = new ArrayCollection();
        $this->rooms = new ArrayCollection();
        $this->keycloakGroups = new ArrayCollection();
        $this->OwnRoomUSer = new ArrayCollection();
        $this->stars = new ArrayCollection();
        $this->tag = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getAppId(): ?string
    {
        return $this->appId;
    }

    public function setAppId(?string $appId): self
    {
        $this->appId = $appId;

        return $this;
    }

    public function getAppSecret(): ?string
    {
        return $this->appSecret;
    }

    public function setAppSecret(?string $appSecret): self
    {
        $this->appSecret = $appSecret;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        $this->user->removeElement($user);

        return $this;
    }

    /**
     * @return Collection|Rooms[]
     */
    public function getRooms(): Collection
    {
        return $this->rooms;
    }

    public function addRoom(Rooms $room): self
    {
        if (!$this->rooms->contains($room)) {
            $this->rooms[] = $room;
            $room->setServer($this);
        }

        return $this;
    }

    public function removeRoom(Rooms $room): self
    {
        if ($this->rooms->removeElement($room)) {
            // set the owning side to null (unless already changed)
            if ($room->getServer() === $this) {
                $room->setServer(null);
            }
        }

        return $this;
    }

    public function getAdministrator(): ?User
    {
        return $this->administrator;
    }

    public function setAdministrator(?User $administrator): self
    {
        $this->administrator = $administrator;

        return $this;
    }

    public function getLogoUrl(): ?string
    {
        return $this->logoUrl;
    }

    public function setLogoUrl(?string $logoUrl): self
    {
        $this->logoUrl = $logoUrl;

        return $this;
    }

    public function getSmtpHost(): ?string
    {
        return $this->smtpHost;
    }

    public function setSmtpHost(?string $smtpHost): self
    {
        $this->smtpHost = $smtpHost;

        return $this;
    }

    public function getSmtpPort(): ?int
    {
        return $this->smtpPort;
    }

    public function setSmtpPort(?int $smtpPort): self
    {
        $this->smtpPort = $smtpPort;

        return $this;
    }

    public function getSmtpPassword(): ?string
    {
        return $this->smtpPassword;
    }

    public function setSmtpPassword(?string $smtpPassword): self
    {
        $this->smtpPassword = $smtpPassword;

        return $this;
    }

    public function getSmtpUsername(): ?string
    {
        return $this->smtpUsername;
    }

    public function setSmtpUsername(?string $smtpUsername): self
    {
        $this->smtpUsername = $smtpUsername;

        return $this;
    }

    public function getSmtpEncryption(): ?string
    {
        return $this->smtpEncryption;
    }

    public function setSmtpEncryption(?string $smtpEncryption): self
    {
        $this->smtpEncryption = $smtpEncryption;

        return $this;
    }

    public function getSmtpEmail(): ?string
    {
        return $this->smtpEmail;
    }

    public function setSmtpEmail(?string $smtpEmail): self
    {
        $this->smtpEmail = $smtpEmail;

        return $this;
    }

    public function getSmtpSenderName(): ?string
    {
        return $this->smtpSenderName;
    }

    public function setSmtpSenderName(?string $smtpSenderName): self
    {
        $this->smtpSenderName = $smtpSenderName;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getSlugMd5(): ?string
    {
        if ($this->isPrefixRoomUidWithHash()) {
            return md5($this->id . $this->slug) . '/';
        } else {
            return '';
        }

    }

    public function getPrivacyPolicy(): ?string
    {
        return $this->privacyPolicy;
    }

    public function setPrivacyPolicy(?string $privacyPolicy): self
    {
        $this->privacyPolicy = $privacyPolicy;

        return $this;
    }

src/Entity/UserBase.php
<?php

namespace App\Entity;

use App\Repository\UserBaseRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

class UserBase implements UserInterface
{
    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $uuid;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column(type: 'string')]
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->uuid;
    }

    /**
     * @return string
     */
    public function getUserIdentifier(): string
    {
        return $this->uuid;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }


    /**
     * @see UserInterface
     */
    public function eraseCredentials():void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }
}

templates/lobby/__callOutParticipants.html.twig
<div class="calloutsymbol d-flex position-relative shadow-2">
    <div class="content  p-2 shadow-2 position-absolute">
        <div class="participantsName d-flex flex-column">
            {% if cU.state > 15 %}
                <p class="badge badge-warning">
                    {% if cU.state == 30 %}
                        {{ 'callout.status.occupied'|trans }}
                    {% elseif cU.state == 40 %}
                        {{ 'callout.status.later'|trans }}
                    {% elseif cU.state == 50 %}
                        {{ 'callout.status.timeout'|trans }}
                    {% endif %}
                </p>
           {% endif %}
            {{ nameOfUserwithFormat(cU.user, laf_showNameFrontend) }}
            {% if cU.leftRetries == 0 %}
                <p class="badge badge-warning no-more-retries">{{ 'callout.info.noMoreRetries'|trans }}</p>
            {% endif %}
        </div>
    </div>
    <div class="ringingsymbol p-2">
        {% if cU.state <= 10 %}
            <i class="fa-2x fa-solid fa-phone text-success fa-fw"></i>
        {% elseif cU.state <= 15 %}
            <i class="fa-2x fa-fw fa-regular fa-bell text-success "></i>
        {% else %}
            <i class="fa-2x fa-solid fa-phone-slash text-warning fa-fw"></i>
        {% endif %}
    </div>

</div>

templates/lobby/__lobbyParticipants.html.twig
{% if wU.websocketReady %}
<div class="col-lg-4 col-12 col-xl-3 waitingUserCard mb-3 position-relative">
    <div class="card ">
        <div class="card-body text-center d-flex justify-content-between flex-row flex-lg-column align-items-center">
            {% if wU.user is not null and  wU.user.profilePicture is not null %}
                <style>
                    #circle_{{ wU.id }} {
                        background-image: url("{{ vich_uploader_asset(wU.user.profilePicture,'documentFile') }}");
                        background-position: center;
                        background-size: cover;
                        background-color: white !important;
                    }
                </style>

            {% endif %}
            <div class="initialCircle d-none d-lg-block" id="circle_{{ wU.id }}">
                {% if wU.user is null or wU.user.profilePicture is  null %}
                    {% if wU.user is not null %}
                        {% if wU.user.firstName != '' %}
                            {{ wU.user.firstName[:1] }}{{ wU.user.lastName[:1] }}
                        {% else %}
                            {{ wU.user.username[:1] }}
                        {% endif %}
                    {% else %}
                        {{ wU.showName[:2] }}
                    {% endif %}
                {% endif %}
            </div>
            <div class="nameHolder">
                <div class="participantsName">{{ wU.showName }}

                </div>
                {% if wU.callerSession is not null %}
                    <div class="participantsName callerId"><i
                                class="fa fa-phone text-success"></i> {{ wU.callerSession.callerId }}</div>
                    {% if wU.callerSession.callerIdVerified %}
                        <span class="callerVerified badge badge-success">{{ 'lobby.verified'|trans }}</span>
                    {% else %}
                        <a class="callerNotVerified badge badge-danger w-100"
                           data-mdb-toggle="popover"
                           data-mdb-trigger="focus"
                           tabindex="0"
                           data-mdb-content="{{ 'lobby.notVerified'|trans }}">
                            <i class="fa-2x fa-solid fa-bolt text-warning"></i>
                        </a>
                    {% endif %}
                {% endif %}
            </div>
            <div class="buttonHolder buttons mt-lg-2 d-flex align-items-center justify-content-between">
                <a
                        data-mdb-toggle="tooltip"
                        title="{{ 'lobby.participant.tooltip.acccept'|trans }}"
                    class="btn btn-lg btn-floating senddirect btn-success "
                   href="{{ path('lobby_moderator_accept',{'wUid':wU.uid}) }}">
                    <i class="fas fa-user-check"></i>
                </a>
                <a
                        data-mdb-toggle="tooltip"
                        title="{{ 'lobby.participant.tooltip.decline'|trans }}"
                        class="btn btn-lg btn-floating directSendWithConfirm btn-danger "
                   data-text="{{ 'confirm.delete.lobbyUser'|trans }}"
                   href="{{ path('lobby_moderator_decline',{'wUid':wU.uid}) }}">
                    <i class="fas fa-user-times"></i>
                </a>


                    <div class="dropdown dropstart"
                         data-mdb-toggle="tooltip"
                         title="{{ 'lobby.participant.tooltip.message'|trans }}"
                    >
                        <a class="btn btn-lg btn-outline-success btn-floating"

                           data-mdb-ripple-color="dark"
                           id="dropdownMenu2"
                           data-mdb-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-solid fa-paper-plane"></i>
                        </a>
                        {% include('lobby/__lobbyMessageDropdown.html.twig') with {'url':path('lobby_send_message_to_waitinguser'),'uid':wU.uid } %}
                    </div>


                </div>
            </div>

        </div>
    </div>
</div>
{% endif %}

templates/lobby/index.html.twig
{% extends 'join/base_fluid.html.twig' %}
{% block header %}
    {% trans with {'{name}':room.name} %}lobby.moderator.title{% endtrans %}
{% endblock %}
{% block content %}
    <div class="col-12 lobbyCard">
        <div id="jitsiWrapper">
            <div class="w-100" id="jitsiWindow">
                {% block sidebar %}
                    {% embed('conference_modules/conferenceSidebar.html.twig') with {'room': room} %}
                        {% block extension %}
                            {% if room.totalOpenRooms == true %}
                                {% include 'conference_modules/inviteUsersToOpenRooms.html.twig' with {'url':path('own_room_startPage',{'uid':room.uid})} %}
                            {% endif %}
                        {% endblock %}
                    {% endembed %}
                {% endblock %}
            </div>
            <div class="row lobbyWindow" id="lobbyWindow">
                <div class="col-lg-3 col-md-6" id="colWebcam">
                    <div class="card webcamArea">
                        <video autoplay="true" id="lobbyWebcam"></video>
                        <div class="webcamToolbar">
                            <i class="fa fa-video me-2" id="webcamSwitch"></i>
                            {{ user.formatedName(laf_showNameInConference) }}
                            {% if user == room.moderator %}
                                <i class="fa fa-crown ms-2"></i>
                            {% endif %}
                        </div>
                    </div>

                    <div class="d-grid">
                        <a class="caretdown btn btn-block btn-primary dropdown-toggle overflow-hidden w-100"
                           type="button"
                           id="selectWebcamDropdown"
                           data-mdb-toggle="dropdown" aria-haspopup="true"
                           aria-expanded="false"><i class="fa fa-video me-2"></i><span
                                    class=" w-100 text-ellipsis text-center">{{ 'lobby.noWebCamFound'|trans }}</span>
                        </a>
                        <ul class="dropdown-menu p-1" aria-labelledby="dropdownMenu1" id="webcamSelect">
                        </ul>


                        <div class="btn-group">

                            <a type="button" class="btn btn-primary dropdown-toggle caretdown"
                               data-mdb-toggle="dropdown"
                               data-mdb-reference="parent"
                               aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-microphone"></i>
                            </a>
                            <div class="dropdown-menu">
                                <div id="audioInputSelect">
                                    <a class="dropdown-item"><b>{{ 'lobby.echo.input'|trans }}</b></a>
                                </div>
                            </div>
                            <a type="button" class="btn btn-primary" id="startEcho"
                               data-texton="{{ 'lobby.start.echo'|trans }}"
                               data-textoff="{{ 'lobby.stop.echo'|trans }}">{{ 'lobby.start.echo'|trans }}</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9 col-md-6" id="col-waitinglist">
                    <div class="dropdown mb-2">
                        <a class="btn btn-lg btn-outline-success btn-rounded" data-mdb-ripple-color="dark"
                           id="dropdownMenu2"
                           data-mdb-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-solid fa-paper-plane"></i> {{ 'lobby.btn.message.to.all'|trans }}
                        </a>
                        {% include('lobby/__lobbyMessageDropdown.html.twig') with {'url':path('lobby_send_message_to_waitinguser_all'),'uid':room.uidReal } %}
                    </div>

                    <div id="waitingUserWrapper">

                        <div id="waitingUser" class="mb-3 d-flex">

                            <div class="activeLobbyUsers flex-grow-1 row">
                                {% for wU in room.lobbyWaitungUsers %}
                                    {% include 'lobby/__lobbyParticipants.html.twig' with {'wu':wU} %}
                                {% endfor %}

                            </div>
                            <div class="onholdPartcipants ms-1 ms-lg-2">
                                {% for cU in room.calloutSessions %}
                                    {% include 'lobby/__callOutParticipants.html.twig' with {'cU':cU} %}
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                    <div class="lobbyButtons">
                        <div class=" flex-grow-1 p-2 d-flex flex-column flex-lg-row align-items-lg-center">
                            {% if type == 'a' %}
                                <a class="btn btn-primary start-btn me-0  me-lg-2 flex-grow-1"
                                   href="{{ path('lobby_moderator_start',{'t':'a','room':room.uidReal}) }}"
                                   target="_blank">
                                    <i class="fa fa-play"></i> {{ 'jitsi.start'|trans }}
                                </a>
                            {% elseif type == 'b' %}
                                {% if room.server.corsHeader %}
                                    <a class="btn btn-primary start-btn  me-0  me-lg-2 flex-grow-1"
                                       href="{{ path('lobby_moderator_start',{'t':'b','room':room.uidReal}) }}"
                                       target="_blank">
                                        <i class="fa fa-play"></i> {{ 'jitsi.start'|trans }}
                                    </a>
                                {% else %}
                                    <a class="btn btn-primary startJitsiIframe  start-btn me-0  me-lg-2 flex-grow-1"
                                       href="{{ path('lobby_moderator_start',{'t':'b','room':room.uidReal}) }}"
                                       target="_blank">
                                        <i class="fa fa-play"></i> {{ 'jitsi.start'|trans }}
                                    </a>
                                {% endif %}
                            {% endif %}

                            <a class="btn btn-success directSend flex-grow-1 me-0  me-lg-2"
                               href="{{ path('lobby_moderator_accept_all',{'roomId':room.uidReal}) }}">{{ 'lobby.allowAllUsers'|trans }}
                            </a>


                            <div class="dropdown flex-grow-1" id="selectAtendeeArea" tabindex="-1">
                                <div class="input-group  w-100">

                                    <div class="form-outline bg-white flex-grow-1">

                                        <input href="{{ path('search_participant') }}"
                                               type="text"
                                               autocomplete=off
                                               id="searchCallOutParticipants"
                                               class="form-control"
                                               placeholder="{{ 'Tippen zum Suchen'|trans }}"
                                        />
                                        <label class="form-label"
                                               for="searchCallOutParticipants">{{ 'Jetzt einladen'|trans }}</label>

                                    </div>

                                    <button class="btn btn-primary"
                                            type="button"
                                            id="addCalloutUserBtn"
                                            data-mdb-ripple-color="dark"
                                            disabled="disabled"
                                            href="{{ path('sip_call_out_invite',{'roomUid':room.uidReal}) }}">
                                        <i class="fa fa-user-plus"></i>
                                    </button>
                                </div>
                                <div data-mdb-toggle="dropdown"
                                     data-mdb-auto-close="false"
                                     id="searchCallOutParticipantsDropdownTrigger">

                                </div>
                                <div class="dropdown-menu searchCallOutParticipantsDropdown"
                                     id="searchCallOutParticipantsDropdown">
                                    <a class="dropdown-item defaultSearch">{{ 'callout.dropdown.empty'|trans }}</a>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>

            </div>

        </div>
    </div>





{% endblock %}
{% block script %}

    {% if name is defined and name is not null %}
        {% if room.server.liveKitServer %}
            <script>
                var livekitUrl = '{{ room.server.livekitMiddlewareUrl?:LIVEKIT_BASE_URL }}/meetling/room/{{ room.uid }}?jwt={{ jwtFromRoom(user,room,name) }}&secret={{ generateEncryptedSecret(room) }}';
                const displayName = '{{ name }}';
            </script>
        {% else %}
            {% include('__checkFirefox.html.twig') with {'room':room} %}
            <script src='https://{{ room.server.url }}/external_api.js'></script>
        {% endif %}

        <script>
            var hangupQuestion = "{{ 'lobby.endMeeting.ask'|trans }}";
            var endMeetingUrl = "{{ path('lobby_Moderator_endMeeting',{'roomUid':room.uidReal}) }}";
            var endMeetingText = "{{ 'lobby.endMeeting'|trans }}";
            var hangupText = "{{ 'lobby.hangup'|trans }}";
            const domain = '{{ room.server.url }}';
            const options = {
                roomName: '{{ room.server.slugMd5 }}{{ room.uid }}',

                width: '100%',
                height: 700,
                configOverwrite: {
                    prejoinPageEnabled: false,
                    disableBeforeUnloadHandlers: true,
                    {% if server.dynamicBrandingUrl %}
                    dynamicBrandingUrl: ' {{ server.dynamicBrandingUrl }}',
                    {% endif %}
                    buttonsWithNotifyClick: [
                        'hangup',
                        '__end'
                    ]
                },
                interfaceConfigOverwrite: {
                    MOBILE_APP_PROMO: false,
                    SHOW_JITSI_WATERMARK: false,
                    HIDE_DEEP_LINKING_LOGO: true,
                    SHOW_BRAND_WATERMARK: false,

                    SHOW_WATERMARK_FOR_GUESTS: false
                },
                parentNode: document.querySelector('#jitsiWindow'),
                {% if room.server.appId is not null %}
                jwt: '{{ jwtFromRoom(user,room,name) }}',
                {% endif %}
                userInfo: {
                    displayName: '{{ name }}',
                    {% if user is not null and  user.profilePicture is not null %}
                    avatarUrl: '{{ vich_uploader_asset(user.profilePicture,'documentFile') }}',
                    {% endif %}
                }
            };

            var conferenzeName = '{{ room.name }}';
            {% if app.user is defined and app.user is not null %}
            {{ mercure([
                'lobby_moderator/'~room.uidReal,
                'lobby_broadcast_websocket/'~ room.uidReal,
                'lobby_personal'~room.uidReal~app.user.uid])|json_encode(constant('JSON_UNESCAPED_SLASHES') b-or constant('JSON_HEX_TAG'))|raw }}
            {% else %}
            {{ mercure([
                'lobby_moderator/'~room.uidReal,
                'lobby_broadcast_websocket/'~ room.uidReal])|json_encode(constant('JSON_UNESCAPED_SLASHES') b-or constant('JSON_HEX_TAG'))|raw }}

            {% endif %}
            {% if app.user is defined and app.user is not null %}
            {% set topics =[
                'lobby_moderator/'~room.uidReal,
                'lobby_broadcast_websocket/'~ room.uidReal,
                'lobby_personal'~room.uidReal~app.user.uid,
                'whiteboard/'~room.uidReal
            ] %}
            {% else %}
            {% set topics =[
                'lobby_moderator/'~room.uidReal,
                'lobby_broadcast_websocket/'~ room.uidReal,
                'whiteboard/'~room.uidReal
            ] %}
            {% endif %}
            var topic ={{ mercure(topics)|json_encode(constant('JSON_UNESCAPED_SLASHES') b-or constant('JSON_HEX_TAG'))|raw }};
            var websocketTopics = "{{ getJwtforWebsocket(topics,app.user) }}";

            var showTagTransparent = {{ getApplicationProperties('LAF_SHOW_TAG_TRANSPARENT_BACKGROUND')==1?'true':'false' }};
        </script>
    {% endif %}
{% endblock %}
{% block webpack %}

    {{ encore_entry_script_tags('lobbyModerator') }}
{% endblock %}